export const quoteParaColsOverride = () => ({
  justifyContent: 'center !important',
  '& blockquote': {
    position: 'relative',
    paddingTop: '2em !important',
    paddingBottom: '0.5em !important',
    '&:before': {
      content: '"“"',
      display: 'block',
      position: 'absolute',
      transform: 'scale(4)',
      left: 'calc(50% - 0.5em)',
      height: '0.5em',
      width: '0.5em',
      borderRadius: '5em',
      zIndex: '3',
      lineHeight: '1.2',
      textAlign: 'center',
      padding: '0.2em',
      top: '0',
    },
    '&:after': {
      content: '""',
      display: 'block',
      position: 'absolute',
      left: '30%',
      right: '30%',
      height: '0',
      borderTop: '0.1em solid',
      zIndex: '2',
      lineHeight: '1',
      opacity: '0.2',
      top: '0.45em',
    },
    '& p': {
      borderLeft: '0 !important',
      marginBottom: '0',
      fontSize: '1.6em !important',
      padding: '0',
    },
  },
});
